// Generated by packages/theme/scripts/generate-icons.mjs from @iconify-json/lucide 1.2.137 (ISC)
// and @iconify-json/simple-icons 1.2.97 (CC0-1.0). Do not edit: change NAME_MAP and run
// `pnpm --filter @ocx-sh/theme icons`.
export type IconName =
  | 'chevron-down'
  | 'chevron-right'
  | 'arrow-right'
  | 'close'
  | 'check'
  | 'alert'
  | 'info'
  | 'success'
  | 'warning'
  | 'error'
  | 'search'
  | 'menu'
  | 'more'
  | 'sort'
  | 'sort-asc'
  | 'sort-desc'
  | 'sun'
  | 'moon'
  | 'monitor'
  | 'minus'
  | 'plus'
  | 'copy'
  | 'download'
  | 'external'
  | 'pin'
  | 'edit'
  | 'trash'
  | 'play'
  | 'pause'
  | 'fullscreen'
  | 'fullscreen-exit'
  | 'globe'
  | 'folder'
  | 'github'
  | 'linux'
  | 'apple'
  | 'windows'
  | 'shell'
  | 'powershell'
  | 'nushell'
  | 'fish'
  | 'elvish'
  | 'cmd';
export type IconGroup = 'interface' | 'action' | 'brand' | 'os' | 'shell';
export type IconDef = {
  viewBox: string;
  /** SVG children, inserted verbatim; no colour of their own (currentColor). */
  body: string;
  /** Line icon: stroke width in viewBox units (the `--ocx-icon-stroke` token overrides it). Absent: filled. */
  stroke?: number;
  group: IconGroup;
  /** Extra words the catalog search matches. */
  keywords: string;
};
export const ICONS: Record<IconName, IconDef>;
/** Registry names in catalog order. */
export const ICON_NAMES: IconName[];
/** Where each glyph comes from (and so its licence). */
export const ICON_SOURCES: Record<IconName, 'lucide' | 'simple-icons' | 'custom'>;
