#:schema https://grimoire.rs/schemas/grimoire-config.schema.json
[options]
clients = ["claude", "codex", "opencode"]

[bundles]
docs-essentials = "ghcr.io/ocx-sh/lore/docs-essentials:latest"
typescript-essentials = "ghcr.io/ocx-sh/lore/typescript-essentials:latest"

[skills]

[rules]
css-theming = "ghcr.io/ocx-sh/lore/css-theming:latest"
